title: Winston's Blog
theme: minima
author: Winston Huang
email: whuang@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  Hi, my name is Winston and I am a graduating senior at EBHS. In high school, I have done clubs in school like Science Honor Society and Science Olympiad
  and outside of school, I have volunteered at the Red Cross and at Sunrise Senior Home.

# social links
instagram_username: winstonhuang # DO NOT include the @ character, or else the build will fail!
github_username:  Winnirn # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
