---
title: "Winston Blog"
date: 2020-06-05
theme: minima
author: "Winston Huang"
email: "whuang@ebnet.org"
description:
  Hi, my name is Winston and I am a graduating senior at EBHS. 
  
  Brag Sheet\
  Science Honor Society\
  Science Olympiad \
  Volunteered at the Red Cross\
  Volunteered Sunrise Senior Home.\

# social links
twitter_username: "winstonhuang" # DO NOT include the @ character, or else the build will fail!
github_username:  "Winnirn" # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
---
